name: Yana Petrova
description: Personal blog
meta_description: "Yana Petrova's blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://janavpetrova.github.io'
author:         'Yana Petrova'

comments:
  provider: facebook
  facebook:
    app_id: 234661286713699